# Dependencies
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            slin32
tagline:          'In two languages'
description:      'Stay humble, and keep learning.'
baseurl:          /